name: Nick
version: 0.6
depends: [ProtocolLib]
author: Timeout
description: A simple NickPlugin

main: de.timeout.nick.Nick

commands:
  nick:
    description: Nicks a Player
  unnick:
    description: Unnicks a Player
  check:
    description: Check a player, if he's nicked.
    
permissions:
  nick.nick:
    description: Needed for /nick
  nick.check:
    description: Needed for /check