name: Nick
version: 0.1-DEV
depends: [ProtocolLib]
author: Timeout
description: A simple NickPlugin

main: de.timeout.nick.Nick

commands:
  nick:
    description: Nicks a Player
  unnick:
    description: Unnicks a Player
    
permissions:
  nick.nick:
    description: Needed for /nick